server:
  port: 1234

movieRepo: 
    apiKey: "eca5e0be68fdba88825606937300d847"
    apis: {
         listAll: "https://api.themoviedb.org/3/movie/557/similar",
         findOne: "https://api.themoviedb.org/3/movie/",
         findRelevant: "https://api.themoviedb.org/3/search/movie"
    }
    
characterRepo:
    apiKey: "fd7015abcc113e71742a9e4de690e18c"
    privateKey: "15ace9ae12eeb6b81e0bed896ed21c0b4fee5443"
    apis: {
         listAll: "https://gateway.marvel.com:443/v1/public/characters"
    }
         
spring: 
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 60   
    
