server:
  port: 1234

movieRepo: 
    apis: {
         listAll: "https://api.themoviedb.org/3/movie/557/similar",
         findOne: "https://api.themoviedb.org/3/movie/",
         findRelevant: "https://api.themoviedb.org/3/search/movie",
         posterURL: "https://image.tmdb.org/t/p/w600_and_h900_bestv2"
    }
    
characterRepo:
    pageSize: 15
    apis: {
         listAll: "https://gateway.marvel.com:443/v1/public/characters"
    }
         
spring: 
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 60   

logging:
  level:
    org.springframework.web : DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: application.log   
jasypt:
  encryptor:
       password: visa@assignment